---
- name: Deploy the DNS servers
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    stack_name: dns-service
    domain_name: example.com
    flavor: m1.small
    slave_count: 3
    slave_server_group_policies: ['anti-affinity']
    contact: admin@{{ domain_name }}
  tasks:
