---
sudo: required

services:
  - docker

cache:
  - pip

language: python
python:
  - "2.7"

install:
  - pip install ansible shade dnspython

script:
  - ansible-galaxy install -r playbooks/provisioning/openstack/galaxy-requirements.yaml -p roles
  - ansible-playbook -i playbooks/provisioning/openstack/sample-inventory/ playbooks/provisioning/openstack/provision.yaml
