---
sudo: required

services:
  - docker

cache:
  - pip

language: python
python:
  - "2.7"

install:
  - pip install ansible python-dns shade

script:
  - ansible-playbook -i playbooks/provisioning/openstack/sample-inventory/ playbooks/provisioning/openstack/provision.yaml
