---
sudo: required

services:
  - docker

cache:
  - pip

language: python
python:
  - "2.7"

install:
- ci/openstack/install.sh

script:
- ci/openstack/provision.sh
- ci/openstack/validate.sh

after_script:
- ci/openstack/teardown.sh
