---
- hosts: localhost
  gather_facts: True
  become: False
  vars_files:
    - stack_params.yaml
  pre_tasks:
    - include: pre_tasks.yml
  roles:
    - role: openstack-stack
    - role: static_inventory
      when: openstack_inventory|default('static') == 'static'
      inventory_path: "{{ openstack_inventory_path|default(inventory_dir) }}"
      private_ssh_key: "{{ openstack_private_ssh_key|default('~/.ssh/id_rsa') }}"

- name: Refresh Server inventory
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  tasks:
    - meta: refresh_inventory

- include: post-provision-openstack.yml
