heat_template_version: 2014-10-16


description: >
  OpenShift Master


parameters:

  key_name:
    description: >
      A pre-submitted SSH key to access the VM hosts
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    description: >
      Select a base image to use for the master servers
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    description: >
      Define the hardware characteristics for the VMs: CPU, Memory, base disk
    type: string
    constraints:
    - custom_constraint: nova.flavor

  root_volume_size:
    description: >
      Size of the root partition
    type: number

  docker_volume_size:
    description: >
      Size of a cinder volume in GB to allocate to docker for
      container/image storage
    type: number

  etcd_volume_size:
    description: >
      Size of a cinder volume in GB to allocate to etcd storage
    type: number

  ssh_user:
    description: >
      The user for SSH access to the VM hosts
    type: string

  external_network:
    description: >
      The name of the inbound access network
    type: string
    constraints:
    - custom_constraint: neutron.network

  control_network:
    description: >
      The name or ID of the admin and public network
    type: string
    constraints:
    - custom_constraint: neutron.network

  control_subnet:
    description: >
      The name or ID of the admin and public IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  tenant_network:
    description: >
      The name or ID of the tenant network for the container traffic
    type: string
    constraints:
    - custom_constraint: neutron.network

  tenant_subnet:
    description: >
      The name or ID of the tenant IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  # TODO
  # master_server_group:
  #   description: >
  #     ID of a server group containing all of the master hosts
  #   type: string

  master_security_group:
    description: >
      ID of the network access policies for the OpenShift master hosts
    type: string

  api_port:
    type: number
    description: The port number for the OpenShift API

  external_lb_pool:
    description: >
      The pool for the load balancer for the external API traffic
    type: string

  internal_lb_pool:
    description: >
      The pool of the load balancer for the internal API traffic
    type: string

resources:

  # Create a network connection on the control communications network
  control_port:
    type: OS::Neutron::Port
    properties:
      security_groups:
      - {get_param: master_security_group}
      network: {get_param: control_network}
      fixed_ips:
      - subnet: {get_param: control_subnet}
      replacement_policy: AUTO

  # Create a network connection on the tenant communications network
  tenant_port:
    # TODO: revert back to the generic/configurable type?
    # type: OOShift::ContainerPort
    type: sdn_openshift_sdn.yaml
    properties:
      security_group: {get_param: master_security_group}
      network: {get_param: tenant_network}
      subnet: {get_param: tenant_subnet}

  # Create the VM instance to host the OpenShift master service
  host:
    type: OS::Nova::Server
    properties:
      admin_user: {get_param: ssh_user}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: control_port}
      - port: {get_attr: [tenant_port, port]}
      block_device_mapping_v2:
      # Create a volume for the root partition:
      - image: {get_param: image}
        device_name: vda
        volume_size: {get_param: root_volume_size}
        delete_on_termination: true
      # user_data_format: SOFTWARE_CONFIG
      # user_data: {get_resource: init}
      # TODO: enable these back!
      # scheduler_hints:
      #   group: {get_param: master_server_group}

  # Create space for Docker containers and images
  docker_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: docker_volume_size}

  # Bind the docker storage to the VM
  docker_volume_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: {get_resource: host}
      volume_id: {get_resource: docker_volume}
      mountpoint: /dev/xvdb

  etcd_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: etcd_volume_size}

  etcd_volume_attach:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: {get_resource: host}
      volume_id: {get_resource: etcd_volume}
      mountpoint: /dev/xvdc

  # Provide access to the Master on the public network
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_resource: control_port}

  external_lbpool_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: external_lb_pool }
      address: {get_attr: [floating_ip, floating_ip_address]}
      protocol_port: { get_param: api_port}
      subnet: {get_param: control_subnet}

  internal_lbpool_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_param: internal_lb_pool }
      address: {get_attr: [floating_ip, floating_ip_address]}
      protocol_port: { get_param: api_port}
      subnet: {get_param: control_subnet}


outputs:
  host:
    description: A reference to the master host identifier
    value: {get_resource: host}
  ip_address:
    description: IP address of the node
    value: {get_attr: [floating_ip, floating_ip_address]}
